apiVersion: v2
description: Web frontend for FTF slurry scheme
name: ffc-future-grants-tech-evaluation
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
