{{- include "ffc-helm-library.container-secret" (list . "ffc-future-grants-tech-evaluation.container-secret") -}}
{{- define "ffc-future-grants-tech-evaluation.container-secret" -}}
stringData:
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  AUTH_USERNAME: {{ .Values.container.authUsername | quote }}
  AUTH_PASSWORD_HASH: {{ .Values.container.authPasswordHash | quote }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.appInsights.key | quote }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
{{- end -}}